dist: xenial
sudo: required

services:
  - docker

language: node_js

node_js:
  - "11"

scala:
  -  "2.12.1"

jdk:
  - openjdk10

cache:
  yarn: true
  directories:
    - node_modules
    - "$HOME/.ivy2"

addons:
  chrome: stable

install:
  - git clone --single-branch --depth 1 https://github.com/dasch-swiss/knora-api.git
  - cd knora-api && make stack-up && make init-db-test && make stack-restart
  - cd ~
  - yarn global add yalc
  - git clone https://github.com/dhlab-basel/knora-api-js-lib && cd knora-api-js-lib && yarn install && yarn yalc-publish
  - cd $TRAVIS_BUILD_DIR

script:
  - yalc remove --all && yalc add @knora/api
  - yarn install
  - yarn build
  - docker build .

